name: microscope_napari
dependencies:
  - python>3.4,<3.9
  - pip
  - pip:
    - PyQt5
    - PyQt5.sip
    - numpy>1.14.6,<1.19.4
    - numba>=0.43.1
    - scipy
    - torch>=1.6
    - opencv-python-headless
    - natsort
    - tqdm
    - imagecodecs
    - tifffile
    - napari
    - pydantic==1.10.10